# Generated by Django 4.2.3 on 2023-08-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from datetime import datetime

def create_data(apps, schema_editor):
    Store = apps.get_model('myapp', 'Store')
    store = Store(title = "대전 낙지 전문점", subtitle = "시그니처 로스팅, 가벼운 식사를 위한 최고의 식당", startTime=datetime.now(), endTime=datetime.now(), distance=39)    
    # store = Store(title = "대전 낙지 전문점", subtitle = "시그니처 로스팅, 가벼운 식사를 위한 최고의 식당", photo=open("images/store.jpg", "w"), startTime=datetime.now(), endTime=datetime.now(), distence=39)
    store.save()
    store2 = Store(title = "BBQ", subtitle = "시그니처 로스팅, 가벼운 식사를 위한 최고의 식당", startTime=datetime.now(), endTime=datetime.now(), distance=12)
    store2.save()
    
    Menu = apps.get_model('myapp', 'Menu')
    menu1 = Menu(store=store, name="낙지", price=10000.0)
    menu1.save()
    menu1_2 = Menu(store=store, name="피자", price=10000.0)
    menu1_2.save()
    menu2 = Menu(store=store2, name="치킨", price=20000.0)
    menu2.save()
    
    User = apps.get_model('myapp', 'UserProfile')
    user = User(userName="Otwooo", points=0, total_steps=0)
    user.save()

    # Menu = apps.get_model('myapp', 'Menu')
    # menu = Menu()
    # menu.save()
    # menu = Menu()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='menu_photos/')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='store_photos/')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('distance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPrice', models.DecimalField(decimal_places=1, max_digits=10)),
                ('endPrice', models.DecimalField(decimal_places=1, max_digits=10)),
                ('endTime', models.DateTimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
            ],
        ),
        migrations.RunPython(create_data),
    ]
